name: Scheduled convert

on:
  push:
    branches: [ master ]
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run script
      run: |
        pipenv run python3 freifunk-node-location-converter.py
    - uses: actions/upload-artifact@v2
      with:
        path: nodes.json
    - uses: actions/upload-artifact@v2
      with:
        path: nodes.json.gz
    
